services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/static
      - ./back/uploads:/var/www/uploads:ro
    networks:
      - camagru-network

  api:
    build:
      context: . #Root du projet
      dockerfile: back/Dockerfile
    volumes:
      - ./back/src/:/app/src
      - ./back/uploads:/app/uploads
      - ./back/overlays:/app/overlays
      - ./back/db:/app/db
    command: npm run dev
    networks:
      - camagru-network
    env_file: # Va ajouter les variables d'environnement du .env dans l'env du container.
      - ./back/.env

networks:
  camagru-network:
    driver: bridge
